### ISSUE TITLE
AC:OD 1.5.0 - Game has to be in windowed mode during injection

### ISSUE THREAD

**Issue by 80KiloMett** [FransBouma/InjectableGenericCameraSystem#100]
Hi,

I just figured out that (for me at least) Assassin's Creed Odyssey has to be in windowed mode when the injection is run. If I run the game, then Win-Tab out of it, run the injection, and activate the game again it'll crash. Same thing happens if I run the injection while the "loading picture" (smaller window with AC:OD cover artwork before the game enters full screen) is shown.

But when I run the game, switch to windowed mode, run the injection and then switch back to full screen, all is fine.

This behaviour is probably not a real bug but I still had to try a few things to get everything working. So I guess it's maybe worth mentioning in the readme.

Thank you very much for the awesome work.

**Comment by FransBouma** [comment]
interesting! Never ran into that, perhaps because I run the game in windowed mode because I can then use SRWE (https://github.com/dtgDTGdtg/SRWE ) to resize the window at will for shots :) It's best to inject the camera when the level is loaded btw, as denuvo tends to decrypt code at the last moment it seems so code that has to be there in the exe isn't available (and injection fails!) till the level is loaded.
