### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by CroftGaming** [FransBouma/InjectableGenericCameraSystem#108]
HJ I wanna use this amazing camera system for fallen order how do I install it do I just extract the fallen order camera system into the main directly? Thanks

**Comment by FransBouma** [comment]
It has a readme, why don't you read it? :P (unpack, run game, run injector, done :) )

**Comment by CroftGaming** [comment]
Ah sorry i couldn't find the read me thank you. 😂😂😂

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HowlingDoll** [comment]
@FransBouma 
Please stop being so aggressive. I’ve commented the other guy thread only because he have exactly the same problem and we both had a hope that it could be fixed. You just could say “No, sorry. I won’t bother with that anymore.” or something. Instead of that you were shouting at us and also have blocked all the threads which are related to that issue. Kinda childish. No offence.

**Comment by HowlingDoll** [comment]
@FransBouma 
;-)

**Comment by FransBouma** [comment]
@HowlingDoll 
What do you want me to do, report you to github so they'll block you? Do you want me to make all cameras private with a banner here on the repository with your name on it as the reason? Yeah call me names, I don't care. 

You have no idea what it takes to keep these cameras working. I spent all my free time I can spare on this system and if I can, I help people out, fix cameras etc. but I also have a life. So if someone comes in nagging I have to fix a camera for a game I don't play anymore, with a crash report I have no idea how to fix, , I simply reply with "I don't know, and can't fix it" and move on, what else is there to do? Invest the rare spare time I have on an issue for some random stranger I don't know? 

Because **that's** what you ask of me. Yes, I'm not friendly now but c'est la vie. I put these cameras up for everyone to use, and keep them updated **when I can**, but that's not 'till the end of time'. 

But whatever man, keep acting like a spoiled brat on someone else's repository, whining for a fix.

**Comment by HowlingDoll** [comment]
@FransBouma 
I'm still laughing from your reaction. Insults, threats, message deleting. Kindergarten level.

> You have no idea what it takes to keep these cameras working.
Indeed. I have "no clue", but somehow I've managed it to work with RE2 without crashes.

Piece of advice: be less aggressive.


/

**Comment by CroftGaming** [comment]
Hi what is going on in this thread, I keep getting notifications HowlingDoll stop giving this guy shit as he does an amazing job and you should be thankful you get anything.. it's not a massive deal you know jesus child you are. If you can't wait or cant accept the Author opinion go else where no one is keeping you here. Anyways you do an amazing job and my 'request' isn't a major issue to the camera it is still amazing regardless... i'm sorry you have to deal with people like him FransBouma keep up the great work!

**Comment by FransBouma** [comment]
@CroftGaming Thanks man :) It's about the RE2 camera that crashes after the last game update when the game tries to play a video and you have the window rendering in the tools set to 'fit' (something the game doesn't allow you to do). I can't fix game engine bugs so I can't fix it. I told them that, but alas....

Anyway, the fallen order camera has been merged into the unreal engine unlocker I wrote btw, see: https://framedsc.github.io/GeneralGuides/universal_ue4_consoleunlocker.htm which brings the console back, timestop etc. so you don't need to inject the fallen order camera additionally to it. :) Cheers!

**Comment by CroftGaming** [comment]
Oooo nice I'll give that a try now! Yea no worries just try do best you can, just annoying ain't it damn updates. 🤣 I just downloaded cals inquistor outfit on nexus mods so will look great!

**Comment by HowlingDoll** [comment]
@CroftGaming 
You mad? Why am I supposed to be thankful for being insulted? Some people just need to learn how to chill.
Just like I said before I've figured out with that issue by myself, but that guy is still trying to prove something that he is the boss over here (lol) with threats, insults, deleting messages. Well, whatever. Not like I am giving a damn thing.

I am out of here.

All the best.

/

**Comment by CroftGaming** [comment]
I'm not trying to insult u, u just need to stop asking all the time and give people patience. That's all u need to do literally. If someone kept nagging me about the same shit every day I would probably say the same thing, but trying to be an ass but stuff takes time and their is more important things to do for the camera than that. It states issues tab for a reason so he will come to the issue when he needs to simple.
