### ISSUE TITLE
Broken since last update [Watch_Dogs]

### ISSUE THREAD

**Issue by Flashby2** [FransBouma/InjectableGenericCameraSystem#120]
Hello, i know it's a very boring and difficult task to do, but the last update broke the camera, there's no other way to get a freecam and it's one of the most usefull tool for this game

It will be really nice and apreciate, thank.

**Comment by vp00** [comment]
If a maintainer goes out of their way to fix this issue, please note that the game's disrupt_b64.dll will differ depending on your platform and region. 

Some parts of asia are still on the old version. For the rest of the world, steam and uplay builds are not the same. Fixing the mod properly would require changing to signature scanning, which probably means porting the code used for other games (watch_dogs 2 already has signature scanning).

In any case, since offsets are simply defined using #define, reworks will be necessary if the mod is to work universally (on all platforms/regions).

**Comment by FransBouma** [comment]
I'm sorry some update broke the tools. I wonder when it's updated tho as the game is very old. Also, as I don't have the game installed anymore nor am I planning to do so (finished it twice already) I don't think I'll fix the tools. 

@vp00 Thanks for the info :) I indeed see the watch_dogs camera is made with one of the first versions of IGCS, where I didn't have any AOB scanning (it uses hardcoded offsets which of course are dependent on the region/version at hand). AOB scanning might fix it properly indeed for all regions, but as I mentioned above, I'm not planning to play this game anymore so I'm not going to fix this camera any time soon.
