### ISSUE TITLE
Don't use this if you use bitdefender!

### ISSUE THREAD

**Issue by TheDemitrius** [FransBouma/InjectableGenericCameraSystem#133]
Bitdefender flagged this as a virus, and then began quarantining every single save file for Cyberpunk 2077. It ignored file exceptions, and just continued removing each and every .sav file, as well as the injector exe.

**Comment by FransBouma** [comment]
I doubt bitdefender would quarantine a save file. It quarantines .exe files. Weird that it qualifies a .net exe as 'a virus'... In any case, it's not, you can decompile it if you want to. I'm sorry this happened tho, sometimes virusscanners give false positives, and because it 'injects' a dll into an exe it might be seen as a 'hostile' app, but this is unavoidable.
