### ISSUE TITLE
Lords of the Fallen

### ISSUE THREAD

**Issue by Keith94** [FransBouma/InjectableGenericCameraSystem#24]
Sorry for the odd question, but can the camera tools be used as an "FOV fix" for playing through the game (i.e. without freecam enabled)? There used to be a Cheat Engine table for changing the FOV, but I saw reports that it doesn't work anymore with the latest version of the game. So I'm looking for a way to change only that, without the other features.

**Comment by FransBouma** [comment]
At the moment the fov is changeable only when the camera is active. I did that because otherwise the fov is kept as you set it with cutscenes as well, which likely ruins them (as they often tend to have lower fov). 

There are two fov writes in the game though, one only used in cutscenes. I'll see if I can enable the other always and enable the 'cut scene fov write' when the camera is active, which would give you a changeable fov during gameplay and the cutscene fov how the game designers intended.

**Comment by FransBouma** [comment]
Implemented. https://github.com/FransBouma/InjectableGenericCameraSystem/tree/master/Cameras/LordsOfTheFallen
